### ISSUE TITLE
请问大神，我这个芯片是不是目前刷不了，并且好像也不在你的待开发列表是么？

### ISSUE THREAD

**Issue by glenq** [teasiu/histb#12]
盒子是魔百盒 CM201-2， 具体跑码信息，如下图：
只是想确认一下，这个芯片是不是没在大神的待支持计划里？
![image](https://user-images.githubusercontent.com/17242230/174478680-4d8778cf-1374-4064-b31d-a4ee582fa229.png)

![image](https://user-images.githubusercontent.com/17242230/174478897-fe9e2e8c-fbc9-4723-9256-5c818e84fc4e.png)

**Comment by teasiu** [comment]
300H的芯片暂不支持
